import React, { useRef } from 'react';
import Rock from './Rock';

const IceSurface = ({ pathHistory, positionChange, storeHistory, shot, gameState }) => {
  const iceRef = useRef();

  return (
    <svg id="ice" ref={iceRef} height="100%" viewBox="0 0 750 1650">
      <rect x="0" y="0" width="100%" height="100%" fill="aliceblue" />
      <rect x="0" y="150" width="100%" height="17" fill="red" />
      <rect x="0" y="1485" width="100%" height="15" fill="blue" />
      <circle
        cx="375"
        cy="1200"
        r="300"
        fill="red"
        stroke="black"
        strokeWidth="5"
      />
      <circle
        cx="375"
        cy="1200"
        r="200"
        fill="aliceblue"
        stroke="black"
        strokeWidth="5"
      />
      <circle
        cx="375"
        cy="1200"
        r="100"
        fill="blue"
        stroke="black"
        strokeWidth="5"
      />
      <circle
        cx="375"
        cy="1200"
        r="37.5"
        fill="aliceblue"
        stroke="black"
        strokeWidth="5"
      />
      <line x1="375" y1="0" x2="375" y2="1650" stroke="black" strokeWidth="5" />
      <line
        x1="0"
        y1="1200"
        x2="750"
        y2="1200"
        stroke="black"
        strokeWidth="5"
      />
      <Rock
        id={1}
        positionChange={positionChange}
        x={50}
        y={50}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={2}
        positionChange={positionChange}
        x={100}
        y={50}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={3}
        positionChange={positionChange}
        x={150}
        y={50}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={4}
        positionChange={positionChange}
        x={200}
        y={50}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={5}
        positionChange={positionChange}
        x={50}
        y={100}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={6}
        positionChange={positionChange}
        x={100}
        y={100}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={7}
        positionChange={positionChange}
        x={150}
        y={100}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={8}
        positionChange={positionChange}
        x={200}
        y={100}
        color="red"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />

      <Rock
        id={9}
        positionChange={positionChange}
        x={500}
        y={50}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={10}
        positionChange={positionChange}
        x={550}
        y={50}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={11}
        positionChange={positionChange}
        x={600}
        y={50}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={12}
        positionChange={positionChange}
        x={650}
        y={50}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={13}
        positionChange={positionChange}
        x={500}
        y={100}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={14}
        positionChange={positionChange}
        x={550}
        y={100}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={15}
        positionChange={positionChange}
        x={600}
        y={100}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
      <Rock
        id={16}
        positionChange={positionChange}
        x={650}
        y={100}
        color="yellow"
        parentRef={iceRef}
        storeHistory={storeHistory}
        pathHistory={pathHistory}
        shot={shot}
        gameState={gameState}
      />
    </svg>
  );
};

export default IceSurface;
